# Generated by Django 6.1 on 2026-08-21 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='Código SKU')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Producto')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio de Venta')),
                ('stock_actual', models.IntegerField(default=0, verbose_name='Existencias en Almacén')),
                ('stock_minimo', models.IntegerField(default=5, verbose_name='Stock Mínimo Permitido')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articulos.categoria', verbose_name='Categoría')),
            ],
        ),
    ]
