# Generated by Django 5.2.5 on 2026-08-28 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos_fotos/', verbose_name='Imagen del Producto'),
        ),
    ]
